#pragma once
#define E7_SWITCHER_WIFI_SSID     "REPLACE_ME"
#define E7_SWITCHER_WIFI_PASSWORD "REPLACE_ME"
#define E7_SWITCHER_ACCOUNT "REPLACE_ME"
#define E7_SWITCHER_PASSWORD "REPLACE_ME"
#define E7_SWITCHER_DEVICE_NAME "REPLACE_ME"
